### ISSUE TITLE
useless use of awk 

### ISSUE THREAD

**Issue by monotek** [dguyhasnoname/k8s-day2-ops#1]
https://github.com/dguyhasnoname/k8s-day2-ops/blob/80f87020047bad97ec49138fa794d2b0a7cd8b62/kubelet/kubelet_check.sh#L15

could be used without awk:

```
kubectl get nodes -o=jsonpath='{range .items[*]}{.metadata.name}{"\n"}'
```
or

```
k get nodes --no-headers -o custom-columns=NAME:.metadata.name
```

**Comment by dguyhasnoname** [comment]
script was updated
