### ISSUE TITLE
Incorrect kube version on k8s-deprecations.sh

### ISSUE THREAD

**Issue by Sarah-E-Greene** [dguyhasnoname/k8s-day2-ops#3]
I found this script from your link on https://github.com/sturrent/k8s-check-deprecated-apis/issues/1, which was very helpful, thank you!

However, i found that there's a bug in the regex for getting the current version:

```
 kubectl get nodes -o json \
>     | jq -r '.items[].status.nodeInfo.kubeletVersion' | uniq | sed 's/\v//g'
v1.18.9-eks-d1db3c
```

This then sets the version incorrectly further in the script:

```
Gathering info of current cluster...
Current k8s version: vv1.18.9-eks-d1db3c
```

With this change, it works correctly:

```
--- k8s-deprecations.sh	2021-03-30 14:25:46.000000000 -0600
+++ k8s-deprecations.sh-new	2021-03-30 14:21:15.000000000 -0600
@@ -46,7 +46,7 @@
     echo "Gathering info of current cluster..."

     current_k8s_version="$(kubectl get nodes -o json \
-    | jq -r '.items[].status.nodeInfo.kubeletVersion' | uniq | sed 's/\v//g')"
+    | jq -r '.items[].status.nodeInfo.kubeletVersion' | uniq | sed 's/^v//g')"

     echo "Current k8s version: v$current_k8s_version"
     version="$(echo $current_k8s_version | sed 's/\(.*\)\..*/\1/').0"
```

**Comment by Sarah-E-Greene** [comment]
Also, the colour BOLD doesn't show up on the solarised-dark colour theme, `BOLD='\033[1;33m'` works well though.

**Comment by dguyhasnoname** [comment]
Thanks @SarahRiley I will get it fixed.

**Comment by dguyhasnoname** [comment]
@SarahRiley I have updated the script with your recommendations. Thanks again for the input. Inputs help to improve the scripts for better UX.

**Comment by Sarah-E-Greene** [comment]
Thanks!  The new version works well.
